name: Build and Release Osmosis

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Verify PyUber integration
      run: |
        python -c "import PyUber; print('PyUber imported successfully')"
        
    - name: Build Osmosis executable
      run: |
        python build_app.py
        
    - name: Verify build output
      run: |
        dir dist
        if (Test-Path "dist\Osmosis.exe") { 
          echo "✅ Osmosis.exe built successfully"
          $size = (Get-Item "dist\Osmosis.exe").Length / 1MB
          echo "📦 Executable size: $([math]::Round($size, 2)) MB"
        } else { 
          echo "❌ Build failed - Osmosis.exe not found"
          exit 1
        }
        
    - name: Create installation package
      run: |
        mkdir release_package
        xcopy /E /I /Y dist release_package
        copy README.md release_package\ -ErrorAction SilentlyContinue
        copy config.json release_package\ -ErrorAction SilentlyContinue
        
        echo '@echo off' > release_package\Install_Osmosis.bat
        echo 'echo Installing Osmosis v2.0...' >> release_package\Install_Osmosis.bat
        echo 'echo Installation complete!' >> release_package\Install_Osmosis.bat
        echo 'pause' >> release_package\Install_Osmosis.bat
        
        echo '@echo off' > release_package\Launch_Osmosis.bat
        echo 'cd /d "%~dp0"' >> release_package\Launch_Osmosis.bat
        echo 'start "" "Osmosis.exe"' >> release_package\Launch_Osmosis.bat
        
    - name: Create ZIP package
      run: |
        $version = if ($env:GITHUB_REF -match 'refs/tags/(.*)') { $matches[1] } else { "dev" }
        $zipName = "Osmosis_${version}_Complete.zip"
        
        Compress-Archive -Path 'release_package\*' -DestinationPath $zipName -CompressionLevel Optimal
        
        $zipSize = (Get-Item $zipName).Length / 1MB
        echo "📦 Package created: $zipName"
        echo "📊 Package size: $([math]::Round($zipSize, 2)) MB"
        echo "PACKAGE_NAME=$zipName" >> $env:GITHUB_ENV
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: osmosis-build-artifacts
        path: Osmosis_*_Complete.zip
        retention-days: 30
        
    - name: Upload to release (on tag push)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: Osmosis_*_Complete.zip
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Build Success Notification
      if: needs.build.result == 'success'
      run: |
        echo "✅ Osmosis build completed successfully!"
        echo "📦 Package is ready for download"
        
    - name: Build Failure Notification
      if: needs.build.result == 'failure'
      run: |
        echo "❌ Osmosis build failed"
        echo "🔍 Check the build logs for details"
