name: Build CTV List GUI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13.1
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.1'
        
    - name: Display Python version
      run: python --version
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_python3131.txt
        
    - name: Validate Python modules
      run: |
        python -c "import sys; print(f'Python version: {sys.version}')"
        python build_validator_python3131.py
        
    - name: Build executable with PyInstaller
      working-directory: src
      run: |
        python -m PyInstaller ../ctvlist_gui_python3131.spec --clean --noconfirm
        
    - name: Test executable
      run: |
        # Test that the executable can start
        cd dist
        timeout 10 .\ctvlist_gui.exe --help || echo "GUI test completed"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ctvlist-gui-python3.13.1
        path: dist/
        retention-days: 30

  build-alternative-runners:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, windows-2019]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13.1
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.1'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_python3131.txt
        
    - name: Build with PyInstaller
      working-directory: src
      run: |
        python -m PyInstaller ../ctvlist_gui_python3131.spec --clean --noconfirm
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ctvlist-gui-${{ matrix.os }}-python3.13.1
        path: dist/
