name: Test Dependencies

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13.1']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies (Linux)
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create logo files
      run: |
        cd src/images
        python create_logos.py
    
    - name: Test dependencies
      run: |
        python test_dependencies.py
    
    - name: Test GUI import (headless)
      run: |
        # Test that the main GUI file can be imported without errors
        python -c "
        import sys
        import os
        sys.path.insert(0, 'src')
        
        # Set up headless display for tkinter
        import tkinter
        
        # Import the main application (without running it)
        try:
            import ctvlist_gui
            print('✅ Main application imports successfully')
        except Exception as e:
            print(f'❌ Import error: {e}')
            sys.exit(1)
        "

  test-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.1'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create logo files
      run: |
        cd src/images
        python create_logos.py
    
    - name: Test dependencies
      run: python test_dependencies.py

  test-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.1'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create logo files
      run: |
        cd src/images
        python create_logos.py
    
    - name: Test dependencies
      run: python test_dependencies.py
